import 'dart:convert';
import 'package:built_value/serializer.dart';
import 'package:test/test.dart';

import 'package:offst_mobile/protocol/common.dart';
import 'package:offst_mobile/protocol/protocol.dart';
import 'package:offst_mobile/utils/json_plugin.dart';


import 'protocol_samples.dart' as samples;

void main() {
  group('common serialize', () {
    /*
    final serBuilder = Serializers().toBuilder();
    for (final commonSer in commonSerializers) {
      serBuilder.add(commonSer);
    }

    Serializers serializers = serBuilder.build();
    */

    final serializersWithPlugin =
        (serializers.toBuilder()..addPlugin(CommJsonPlugin())).build();

    test('PublicKey serialization', () {
      final publicKey = PublicKey('MyPublicKey');
      final serialized = serializersWithPlugin.serialize(publicKey,
          specifiedType: FullType(PublicKey));

      JsonEncoder encoder = JsonEncoder.withIndent('  ');
      String jsonString = encoder.convert(serialized);
      // We expect a single string, without a wrap:
      expect(jsonString, '"MyPublicKey"');

      final decoder = JsonDecoder();
      final serialized2 = decoder.convert(jsonString);
      final publicKey2 = serializersWithPlugin.deserialize(serialized2,
          specifiedType: FullType(PublicKey));

      expect(publicKey, publicKey2);

    });
    test('NodeInfoLocal serialization', () {
      final nodeInfoLocal = NodeInfoLocal((b) => b..nodePublicKey = PublicKey('MyPublicKey'));
      final serialized = serializersWithPlugin.serialize(nodeInfoLocal,
          specifiedType: FullType(NodeInfoLocal));

      JsonEncoder encoder = JsonEncoder.withIndent('  ');
      String jsonString = encoder.convert(serialized);

      final decoder = JsonDecoder();
      final serialized2 = decoder.convert(jsonString);
      final nodeInfoLocal2 = serializersWithPlugin.deserialize(serialized2,
          specifiedType: FullType(NodeInfoLocal));

      expect(nodeInfoLocal, nodeInfoLocal2);

    });

    test('Autogenerated samples serialization: ServerToUser', () {
      JsonEncoder encoder = JsonEncoder.withIndent('  ');
      final decoder = JsonDecoder();

      for (final jsonString1 in samples.serverToUser) {
        // Attempt to deserialize:
        final serialized1 = decoder.convert(jsonString1);
        final msg = serializersWithPlugin.deserialize(serialized1,
            specifiedType: FullType(ServerToUser));

        // Make sure that serialization works:
        final serialized2 = serializersWithPlugin.serialize(msg,
            specifiedType: FullType(ServerToUser));
        String jsonString2 = encoder.convert(serialized2);

      }
    });

    test('Autogenerated samples serialization: UserToServer', () {
      JsonEncoder encoder = JsonEncoder.withIndent('  ');
      final decoder = JsonDecoder();

      for (final jsonString1 in samples.userToServer) {
        // Attempt to deserialize:
        final serialized1 = decoder.convert(jsonString1);
        final msg = serializersWithPlugin.deserialize(serialized1,
            specifiedType: FullType(UserToServer));

        // Make sure that serialization works:
        final serialized2 = serializersWithPlugin.serialize(msg,
            specifiedType: FullType(UserToServer));
        String jsonString2 = encoder.convert(serialized2);

      }
    });
  });
}
