targets:
  $default:
    builders:
      offset|wrapped_string:
        enabled: true
      offset|wrapped_bigint:
        enabled: true

builders:
  wrapped_string:
    target: ":offset"
    import: "package:offset/utils/wrapped_string_builder.dart"
    builder_factories: ["wrappedStringBuilder"]
    build_extensions: {".dart": [".wrapped_string.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  wrapped_bigint:
    target: ":offset"
    import: "package:offset/utils/wrapped_bigint_builder.dart"
    builder_factories: ["wrappedBigIntBuilder"]
    build_extensions: {".dart": [".wrapped_bigint.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
