#!/usr/bin/env bash

# Download Offset's stcompact binaries

# See: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -eux -o pipefail

VERSION="0.1.3"
DOWNLOAD_URL="https://github.com/freedomlayer/offset/releases/download"

# curl -L https://capnproto.org/capnproto-c++-${CAPNP_VERSION}.tar.gz | tar -zxf -
# pushd capnproto-c++-${CAPNP_VERSION}

# Remove previous external files:
rm -rf ./external
# Create external directory:
mkdir -p ./external

# Create a temporary directory:
TEMP_DIR=$(mktemp -d -t ci-XXXXXXXXXX)

# aarch64
curl -L "${DOWNLOAD_URL}/v${VERSION}/offset-v${VERSION}-aarch64-linux-android.tar.gz" \
        | tar -zxf - -C $TEMP_DIR
cp $TEMP_DIR/bin/stcompact ./external/stcompact_aarch64
rm -rf $TEMP_DIR/*

# armv7
curl -L "${DOWNLOAD_URL}/v${VERSION}/offset-v${VERSION}-armv7-linux-androideabi.tar.gz" \
        | tar -zxf - -C $TEMP_DIR
cp $TEMP_DIR/bin/stcompact ./external/stcompact_armv7
rm -rf $TEMP_DIR/*

# i686
curl -L "${DOWNLOAD_URL}/v${VERSION}/offset-v${VERSION}-i686-linux-android.tar.gz" \ 
        tar -zxf - -C $TEMP_DIR
cp $TEMP_DIR/bin/stcompact ./external/stcompact_i686
rm -rf $TEMP_DIR/*

# Remote temporary directory
rm -rf ${TEMP_DIR}

