#!/usr/bin/env bash

# See: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -eux -o pipefail

echo "*** Formatting ..."
dartfmt -w $(find bin lib test -name \*.dart 2>/dev/null)

# Compile time code generation
echo "*** Building ..."
flutter pub run build_runner build \
        --delete-conflicting-outputs \
        --fail-on-severe

echo "*** Analyzing ..."
dartanalyzer \
        --fatal-warnings \
        --fatal-infos \
        --packages="$PWD/.packages" \
        $(find bin lib test -name \*.dart 2>/dev/null)

echo "*** Testing ..."
flutter pub run test
